import { writeFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { unifiedDiff, type DiffStats } from '../lib/unifiedDiff.js';
import { scopedFilesService, resolveWithin, ScopeError, EDITABLE_ROOTS } from './scopedFiles.service.js';

// Propose, review, apply. Never propose-and-apply.
//
// A write tool a model can call directly is the whole risk in one line: the
// moment a run has read a product description or an imported PDF, text an
// attacker controls is in the context deciding what gets written. So `apply`
// does not take content — it takes the ID of a proposal a human has already
// seen. The content was frozen when the proposal was created, so it cannot be
// swapped afterwards.
//
// Same shape as findReplace.preview()/execute(), which already works this way
// for site-wide content edits.

export interface Proposal {
  id: string;
  target: { kind: 'file'; root: string; path: string } | { kind: 'custom-css'; userId: string };
  label: string;
  before: string;
  after: string;
  diff: string;
  stats: DiffStats;
  createdAt: number;
  /** Set once applied, so an approved id cannot be replayed to write twice. */
  appliedAt?: number;
  warnings: string[];
}

export interface AppliedResult {
  id: string;
  label: string;
  applied: true;
  stats: DiffStats;
  /** Sidecar copy of the previous contents — this IS the undo. Both editable
   *  roots are gitignored, so there is no commit to revert. */
  backup?: string;
  warnings: string[];
}

// In memory, deliberately not persisted. A proposal is a short-lived review
// artefact: if the process restarts, the right behaviour is to re-read the
// file and propose again against current content, not to apply a diff computed
// against a version that may no longer exist.
const proposals = new Map<string, Proposal>();

const PROPOSAL_TTL_MS = 30 * 60 * 1000;

function sweep(): void {
  const cutoff = Date.now() - PROPOSAL_TTL_MS;
  for (const [id, p] of proposals) if (p.createdAt < cutoff) proposals.delete(id);
}

export const editProposalService = {
  get(id: string): Proposal | undefined {
    sweep();
    return proposals.get(id);
  },

  /** Metadata only — the before/after contents are withheld. */
  list(): Omit<Proposal, 'before' | 'after'>[] {
    sweep();
    return [...proposals.values()].map(({ before: _b, after: _a, ...rest }) => rest);
  },

  /** Diff against CURRENT content and hold it for review. Writes nothing. */
  async proposeFile(root: string, path: string, content: string): Promise<Proposal> {
    sweep();
    const before = await scopedFilesService.read(root, path);
    const { text, stats } = unifiedDiff(before, content, `${root}/${path}`);
    if (stats.identical) throw new ScopeError('That produces no change.');

    const rootDef = EDITABLE_ROOTS.find((r) => r.id === root);
    const warnings: string[] = [];
    if (rootDef?.gitignored) {
      warnings.push(
        'Not tracked in git, so there is no commit to revert. A timestamped .bak copy of the current contents is written next to the file on apply — that is the undo.',
      );
    }
    if (root === 'chrome-css') {
      warnings.push('Partly generated by generate-live-diff.py — re-running the generator discards this edit.');
    }

    const proposal: Proposal = {
      id: randomUUID(),
      target: { kind: 'file', root, path },
      label: `${root}/${path}`,
      before,
      after: content,
      diff: text,
      stats,
      createdAt: Date.now(),
      warnings,
    };
    proposals.set(proposal.id, proposal);
    return proposal;
  },

  async proposeCustomCss(userId: string, content: string): Promise<Proposal> {
    sweep();
    const before = await scopedFilesService.readCustomCss(userId);
    const { text, stats } = unifiedDiff(before, content, 'custom CSS');
    if (stats.identical) throw new ScopeError('That produces no change.');
    const proposal: Proposal = {
      id: randomUUID(),
      target: { kind: 'custom-css', userId },
      label: 'Custom CSS',
      before,
      after: content,
      diff: text,
      stats,
      createdAt: Date.now(),
      warnings: ['Sanitised on save — @import, expression() and script-bearing url() are stripped.'],
    };
    proposals.set(proposal.id, proposal);
    return proposal;
  },

  /**
   * Apply a proposal a human approved.
   *
   * Re-reads first: if the file changed since the proposal was made, the diff
   * that was approved is not the change that would land, so this refuses
   * rather than silently overwriting someone else's edit.
   */
  async apply(id: string): Promise<AppliedResult> {
    sweep();
    const p = proposals.get(id);
    if (!p) throw new ScopeError('No such proposal — it may have expired. Re-read the file and propose again.');
    if (p.appliedAt) throw new ScopeError('That proposal has already been applied.');

    const warnings = [...p.warnings];

    if (p.target.kind === 'custom-css') {
      const current = await scopedFilesService.readCustomCss(p.target.userId);
      if (current !== p.before) {
        throw new ScopeError('Custom CSS changed since this was proposed. Re-read and propose again.');
      }
      await scopedFilesService.writeCustomCss(p.target.userId, p.after);
      p.appliedAt = Date.now();
      return { id, label: p.label, applied: true, stats: p.stats, warnings };
    }

    const { root, path } = p.target;
    const current = await scopedFilesService.read(root, path);
    if (current !== p.before) {
      throw new ScopeError(`${p.label} changed since this was proposed. Re-read and propose again.`);
    }

    // BOTH roots are gitignored — bricks-addons/ via .gitignore line 34, and
    // uploads/ likewise — so there is no commit to revert and this sidecar is
    // the only real undo. An earlier version of this ran `git add` first and
    // silently did nothing, which made the revert story fiction.
    const abs = await resolveWithin(root, path);
    const stamp = new Date(p.createdAt).toISOString().replace(/[:.]/g, '-');
    const backup = `${abs}.bak-${stamp}`;
    await writeFile(backup, p.before, 'utf8');

    await scopedFilesService.write(root, path, p.after);
    p.appliedAt = Date.now();

    return { id, label: p.label, applied: true, stats: p.stats, backup, warnings };
  },

  discard(id: string): boolean {
    return proposals.delete(id);
  },
};
