// The exact classes the reference site gives each Elementor element, keyed by
// element id. Harvested from every page of the reference by tools/harvest-classes.mjs.
//
// This exists because synthesising these names does not work. Our importer knows
// an element as a Bricks `button`, so the obvious guess is
// `elementor-widget-button` — but the reference calls it
// `elementor-widget-ideapark-button`, and the stylesheet is written against
// that. Every wrong guess meant no rule matched and the element rendered at its
// content size: the hero buttons came out 143px against the reference's 306px,
// the logo and scroll arrow shrank the same way.
//
// Forge's source-router rule covers exactly this — route to the real source and
// pull it live, never invent a name the source owns. So these are read off the
// source rather than derived. Ids absent here keep the generic treatment.
export const PORTED_ELEMENT_CLASSES: Record<string, string> = {
  "001a073": "elementor-widget elementor-widget-heading",
  "0071ca2": "elementor-widget elementor-widget-ideapark-accordion",
  "00d8f63": "elementor-widget elementor-widget-heading",
  "0330ac5": "e-con-full e-flex e-con e-child",
  "03477b6": "elementor-widget elementor-widget-n-accordion",
  "035fdb4": "e-con-full e-flex e-con e-child",
  "036957b": "e-con-full e-flex e-con e-parent",
  "0426091": "e-con-full e-flex e-con e-child",
  "04af8da": "elementor-widget elementor-widget-text-editor",
  "0557e21": "elementor-widget elementor-widget-heading",
  "0761e5e": "elementor-widget elementor-widget-spacer",
  "084d34c": "elementor-widget elementor-widget-ideapark-button",
  "0897867": "elementor-widget elementor-widget-spacer",
  "08c404f": "e-con-full e-flex e-con e-parent",
  "08e089a": "elementor-widget elementor-widget-ideapark-button",
  "0956f3a": "elementor-widget elementor-widget-ideapark-news-carousel",
  "09907f9": "elementor-widget elementor-widget-spacer",
  "0a5c33a": "elementor-widget elementor-widget-heading",
  "0cbf5aa": "elementor-widget elementor-widget-heading",
  "0e291aa": "elementor-widget elementor-widget-ideapark-button",
  "0e542f6": "elementor-widget elementor-widget-spacer",
  "0edf8e8": "elementor-widget elementor-widget-spacer",
  "0f1c2c6": "e-con-full e-flex e-con e-child",
  "0f31e51": "elementor-widget elementor-widget-heading",
  "10513c0": "e-con-full e-flex e-con e-parent",
  "1052349": "no-wrap-text elementor-widget elementor-widget-heading",
  "1140037": "elementor-widget elementor-widget-spacer",
  "11abed2": "e-con-full e-flex e-con e-child",
  "129da96": "elementor-widget__width-initial elementor-hidden-mobile elementor-widget elementor-widget-image",
  "135795c": "e-con-full e-flex e-con e-parent",
  "1357cd4": "elementor-widget elementor-widget-heading",
  "155e740": "elementor-widget elementor-widget-text-editor",
  "15ee3dd": "elementor-widget elementor-widget-text-editor",
  "163aa10": "elementor-widget elementor-widget-text-editor",
  "16b01e7": "elementor-widget elementor-widget-ideapark-running-line",
  "16d695e": "elementor-widget elementor-widget-spacer",
  "17961fb": "elementor-widget elementor-widget-spacer",
  "1802ac9": "e-con-full e-flex e-con e-child",
  "18324df": "elementor-widget elementor-widget-heading",
  "18a5a67": "elementor-widget elementor-widget-ideapark-news-carousel",
  "19061e9": "elementor-widget elementor-widget-heading",
  "191250d": "elementor-widget elementor-widget-heading",
  "19d33f2": "e-con-full e-flex e-con e-child",
  "1a50969": "elementor-widget elementor-widget-spacer",
  "1b65fa6": "elementor-widget elementor-widget-heading",
  "1c3220b": "e-con-full e-flex e-con e-child",
  "1c685fd": "elementor-widget elementor-widget-heading",
  "1c709ec": "elementor-widget elementor-widget-heading",
  "1ca21fa": "e-con-full e-flex e-con e-parent",
  "1cb789a": "elementor-widget elementor-widget-spacer",
  "1e5dcf1": "elementor-widget elementor-widget-text-editor",
  "1ea8316": "elementor-widget elementor-widget-heading",
  "1eb3b55": "elementor-widget__width-initial elementor-hidden-mobile elementor-widget elementor-widget-image",
  "1ef23fe": "e-con-full e-flex e-con e-child",
  "1f206ad": "e-con-full e-flex e-con e-parent",
  "1f3b3f8": "e-con-full e-transform elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile e-flex e-con e-child",
  "1fc93c4": "elementor-widget elementor-widget-heading",
  "1ffda3d": "e-con-full e-flex e-con e-parent",
  "20e3f44": "e-con-full e-flex e-con e-parent",
  "214c150": "e-con-full e-flex e-con e-parent",
  "2164cec": "elementor-widget elementor-widget-heading",
  "21c03cb": "elementor-widget elementor-widget-spacer",
  "21fd440": "elementor-widget elementor-widget-heading",
  "222587a": "elementor-widget elementor-widget-spacer",
  "228b609": "elementor-widget elementor-widget-text-editor",
  "23479e5": "elementor-widget elementor-widget-heading",
  "234c56e": "e-con-full e-flex e-con e-parent",
  "2398e30": "elementor-widget elementor-widget-heading",
  "24b22ca": "elementor-widget elementor-widget-ideapark-social",
  "2538e59": "elementor-widget elementor-widget-spacer",
  "25ec685": "elementor-widget elementor-widget-text-editor",
  "260ceae": "elementor-widget elementor-widget-spacer",
  "26751a7": "e-con-full e-flex e-con e-child",
  "26d2f2e": "elementor-widget elementor-widget-heading",
  "28391e5": "e-con-full h-full e-flex e-con e-child",
  "2850778": "elementor-widget elementor-widget-heading",
  "2914d05": "elementor-widget elementor-widget-heading",
  "292e4b0": "elementor-widget elementor-widget-text-editor",
  "2932869": "e-con-full e-flex e-con e-parent",
  "2976e17": "elementor-widget elementor-widget-spacer",
  "297bc47": "e-con-full e-flex e-con e-parent",
  "2a2d6f1": "e-con-boxed e-flex e-con e-parent",
  "2be10ce": "e-flex e-con-boxed e-con e-parent",
  "2cd9bb2": "elementor-widget elementor-widget-heading",
  "2d11987": "e-con-full e-flex e-con e-parent",
  "2d6a709": "elementor-widget elementor-widget-text-editor",
  "2d91460": "elementor-widget elementor-widget-ideapark-accordion",
  "2d92a9d": "elementor-widget elementor-widget-google_maps",
  "2e9a09b": "elementor-widget elementor-widget-text-editor",
  "2fbe000": "elementor-widget elementor-widget-heading",
  "2fcbe81": "elementor-widget elementor-widget-spacer",
  "2ff5950": "elementor-widget elementor-widget-ideapark-button",
  "31065c1": "e-con-full e-flex e-con e-parent",
  "316ac1f": "e-con-full e-flex e-con e-parent",
  "319c23c": "elementor-widget elementor-widget-spacer",
  "331a4ab": "e-con-full e-flex e-con e-parent",
  "3453696": "e-con-full e-flex e-con e-parent",
  "34685d1": "e-con-full e-flex e-con e-parent",
  "348c862": "elementor-widget elementor-widget-spacer",
  "3535483": "elementor-widget elementor-widget-heading",
  "3554579": "e-con-full e-flex e-con e-parent",
  "36944d7": "elementor-widget elementor-widget-heading",
  "36d20ae": "elementor-widget elementor-widget-spacer",
  "375d1e9": "elementor-widget elementor-widget-heading",
  "38588ea": "elementor-widget elementor-widget-heading",
  "386550f": "elementor-widget elementor-widget-ideapark-running-line",
  "387518c": "elementor-widget elementor-widget-heading",
  "394d9b5": "elementor-widget elementor-widget-spacer",
  "39c6790": "e-con-full e-flex e-con e-parent",
  "3abfa46": "elementor-widget elementor-widget-heading",
  "3ba2131": "elementor-widget elementor-widget-text-editor",
  "3ba89e5": "e-con-full e-flex e-con e-parent",
  "3bf3a97": "elementor-widget elementor-widget-heading",
  "3bf7316": "e-con-full e-flex e-con e-parent",
  "3bff7d5": "e-con-full e-flex e-con e-parent",
  "3cd23f8": "e-con-full e-flex e-con e-parent",
  "3cd3976": "elementor-widget elementor-widget-heading",
  "3d6ee5b": "elementor-widget elementor-widget-heading",
  "3e814e0": "elementor-widget elementor-widget-text-editor",
  "3e8f3ec": "e-con-full e-flex e-con e-parent",
  "3ed20a8": "elementor-widget elementor-widget-heading",
  "3ee5f6a": "elementor-widget elementor-widget-text-editor",
  "3f2b444": "elementor-widget elementor-widget-image",
  "3f89f24": "elementor-widget elementor-widget-heading",
  "408664f": "elementor-widget elementor-widget-heading",
  "409b029": "elementor-widget elementor-widget-spacer",
  "413d7c2": "elementor-widget elementor-widget-heading",
  "418d0a9": "e-con-full e-flex e-con e-parent",
  "42c57b6": "elementor-widget elementor-widget-heading",
  "43ffe6a": "elementor-widget elementor-widget-spacer",
  "4491087": "elementor-widget elementor-widget-heading",
  "4539452": "elementor-widget elementor-widget-heading",
  "457b465": "e-con-full e-flex e-con e-parent",
  "45c4e43": "elementor-widget elementor-widget-text-editor",
  "45c94f0": "elementor-widget elementor-widget-spacer",
  "467e354": "elementor-widget elementor-widget-heading",
  "479c7f3": "elementor-widget__width-initial elementor-widget-tablet__width-auto elementor-hidden-mobile elementor-widget elementor-widget-image",
  "4832339": "elementor-widget elementor-widget-ideapark-social",
  "4834d55": "elementor-widget elementor-widget-text-editor",
  "483652e": "elementor-widget elementor-widget-spacer",
  "48734d4": "e-con-full e-flex e-con e-parent",
  "48957b7": "e-con-full e-flex e-con e-child",
  "48be785": "e-con-full e-flex e-con e-parent",
  "490518a": "elementor-widget elementor-widget-heading",
  "4950bbd": "elementor-widget elementor-widget-spacer",
  "49af89d": "elementor-widget elementor-widget-heading",
  "49e3faf": "e-con-full e-flex e-con e-child",
  "4a250f4": "rotated-glyph elementor-widget elementor-widget-heading",
  "4afac67": "elementor-widget elementor-widget-spacer",
  "4b13506": "elementor-widget elementor-widget-heading",
  "4b16452": "e-con-boxed e-flex e-con e-parent",
  "4b1c32f": "elementor-widget elementor-widget-heading",
  "4b725eb": "e-con-full e-flex e-con e-parent",
  "4c5f37f": "e-con-full e-flex e-con e-child",
  "4d297e5": "elementor-widget elementor-widget-ideapark-button",
  "4dc03ab": "elementor-widget elementor-widget-spacer",
  "4e034cc": "e-con-full e-flex e-con e-parent",
  "4e4a1f9": "e-con-full e-flex e-con e-parent",
  "4e55af6": "e-con-boxed e-flex e-con e-parent",
  "4f9a014": "elementor-widget elementor-widget-spacer",
  "50c6c5e": "elementor-widget elementor-widget-ideapark-banners",
  "510e33c": "elementor-widget__width-initial h-form-inverse elementor-widget elementor-widget-shortcode",
  "51199c4": "elementor-widget elementor-widget-image",
  "51421fd": "elementor-widget elementor-widget-spacer",
  "51652e5": "elementor-widget elementor-widget-heading",
  "5197f9d": "e-con-full e-flex e-con e-parent",
  "5212e84": "e-con-full e-flex e-con e-parent",
  "5216a9d": "elementor-widget elementor-widget-spacer",
  "529cb60": "elementor-widget elementor-widget-spacer",
  "5352eca": "elementor-widget elementor-widget-heading",
  "54271f9": "e-con-full e-flex e-con e-parent",
  "54daba0": "e-con-full e-flex e-con e-parent",
  "54fb905": "e-con-full h-full e-flex e-con e-parent",
  "55db45f": "elementor-widget elementor-widget-heading",
  "55fe79b": "e-con-full e-flex e-con e-parent",
  "56f7cb8": "elementor-widget elementor-widget-heading",
  "57de29a": "elementor-widget elementor-widget-spacer",
  "595ab71": "elementor-widget elementor-widget-heading",
  "5962729": "e-flex e-con-boxed e-con e-parent",
  "5994a16": "e-con-full e-flex e-con e-parent",
  "59dfb6a": "e-con-full e-flex e-con e-parent",
  "5b56a1d": "e-con-full e-flex e-con e-parent",
  "5b75228": "elementor-widget elementor-widget-spacer",
  "5b95f66": "e-con-full e-flex e-con e-parent",
  "5bb9e52": "elementor-widget elementor-widget-spacer",
  "5c7f922": "e-con-full e-flex e-con e-parent",
  "5c8c063": "elementor-widget elementor-widget-heading",
  "5c9433d": "e-con-full e-flex e-con e-parent",
  "5cc1cfe": "e-con-full e-flex e-con e-parent",
  "5d1e6ed": "elementor-widget elementor-widget-heading",
  "5e0d2a9": "elementor-widget elementor-widget-text-editor",
  "5e99f07": "elementor-widget elementor-widget-text-editor",
  "5f3c5ab": "elementor-widget elementor-widget-heading",
  "5f42c21": "e-con-full e-flex e-con e-parent",
  "5f6596e": "elementor-widget elementor-widget-spacer",
  "5fe9e4b": "e-con-full e-flex e-con e-parent",
  "6002888": "e-con-full e-flex e-con e-child",
  "6014b4e": "e-con-full e-flex e-con e-parent",
  "60211b3": "elementor-widget elementor-widget-spacer",
  "6086c13": "elementor-widget elementor-widget-heading",
  "60fb402": "elementor-widget elementor-widget-text-editor",
  "613ee75": "e-con-full e-flex e-con e-parent",
  "61685d7": "elementor-widget elementor-widget-heading",
  "61bd3cc": "e-con-full e-flex e-con e-child",
  "62e0485": "elementor-widget elementor-widget-heading",
  "63a60b5": "elementor-widget elementor-widget-heading",
  "63a81bf": "elementor-widget elementor-widget-ideapark-button",
  "63f6eab": "elementor-widget elementor-widget-text-editor",
  "656d992": "elementor-widget elementor-widget-spacer",
  "65b6436": "elementor-widget elementor-widget-spacer",
  "65c1b1e": "elementor-widget elementor-widget-spacer",
  "66c7f39": "e-con-full e-flex e-con e-child",
  "673968f": "elementor-widget elementor-widget-heading",
  "674fff9": "elementor-widget elementor-widget-heading",
  "67e0ab0": "elementor-widget elementor-widget-heading",
  "68c08ef": "elementor-widget elementor-widget-heading",
  "69456b7": "elementor-widget elementor-widget-text-editor",
  "6950d1f": "elementor-widget elementor-widget-spacer",
  "695cab4": "elementor-widget elementor-widget-text-editor",
  "696e30d": "elementor-widget elementor-widget-heading",
  "69fbb65": "elementor-widget elementor-widget-spacer",
  "6a045d4": "elementor-widget__width-initial elementor-widget elementor-widget-text-editor",
  "6aaf83c": "elementor-widget elementor-widget-spacer",
  "6b664c6": "elementor-widget__width-initial elementor-widget elementor-widget-heading",
  "6b726c8": "elementor-widget elementor-widget-spacer",
  "6bfe5a7": "elementor-widget elementor-widget-heading",
  "6c2e99d": "elementor-widget elementor-widget-heading",
  "6c2eb79": "elementor-widget elementor-widget-heading",
  "6c90e8a": "elementor-widget elementor-widget-heading",
  "6c9a7d2": "e-con-full e-flex e-con e-parent",
  "6c9ac73": "e-con-full e-flex e-con e-parent",
  "6cb0ba7": "elementor-widget elementor-widget-heading",
  "6d186b5": "elementor-widget elementor-widget-text-editor",
  "6d18fa8": "elementor-widget elementor-widget-text-editor",
  "6d62cb9": "e-con-full e-flex e-con e-parent",
  "6d924c3": "e-con-full e-flex e-con e-parent",
  "6dfbfe6": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "6e15605": "elementor-widget elementor-widget-wpforms",
  "6e1bed4": "elementor-widget elementor-widget-spacer",
  "6e36e55": "elementor-widget elementor-widget-spacer",
  "6f0850e": "elementor-widget elementor-widget-spacer",
  "6fc20ee": "e-con-full e-flex e-con e-parent",
  "6ff179f": "elementor-widget elementor-widget-heading",
  "7114173": "e-con-full e-flex e-con e-parent",
  "721d995": "e-con-full e-flex e-con e-parent",
  "73737c3": "elementor-widget elementor-widget-heading",
  "743102d": "elementor-widget elementor-widget-heading",
  "748153b": "elementor-widget elementor-widget-heading",
  "74b1a1c": "elementor-widget elementor-widget-spacer",
  "74d6780": "elementor-widget elementor-widget-text-editor",
  "75b419a": "elementor-widget elementor-widget-spacer",
  "75c6036": "elementor-widget elementor-widget-heading",
  "76239e1": "elementor-widget elementor-widget-spacer",
  "7658ac8": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "773ee02": "e-con-full e-flex e-con e-parent",
  "77482e1": "elementor-widget elementor-widget-spacer",
  "7793af2": "e-con-full e-flex e-con e-parent",
  "77d49a9": "elementor-widget elementor-widget-heading",
  "7810284": "e-con-full h-full e-flex e-con e-child",
  "7891959": "elementor-widget elementor-widget-heading",
  "78e4a49": "elementor-widget elementor-widget-spacer",
  "7917d17": "e-con-full e-flex e-con e-child",
  "7917e92": "e-con-full e-flex e-con e-parent",
  "799c606": "elementor-widget elementor-widget-heading",
  "79c799e": "e-con-full e-flex e-con e-parent",
  "7a64e7e": "e-con-full e-flex e-con e-parent",
  "7b0e581": "e-con-full e-flex e-con e-parent",
  "7b19cf3": "e-con-full e-flex e-con e-parent",
  "7b3605e": "e-con-full e-flex e-con e-parent",
  "7bc2018": "e-con-full e-flex e-con e-parent",
  "7c46397": "elementor-widget elementor-widget-spacer",
  "7c8d445": "elementor-widget elementor-widget-spacer",
  "7caae55": "e-con-full e-flex e-con e-parent",
  "7d66b33": "e-con-full e-flex e-con e-parent",
  "7d7a0ac": "elementor-widget elementor-widget-spacer",
  "7dcf2a1": "elementor-widget elementor-widget-spacer",
  "7e92dfd": "e-con-full h-full e-flex e-con e-parent",
  "7ebe7cd": "e-con-full e-flex e-con e-parent",
  "7ecb669": "elementor-widget elementor-widget-text-editor",
  "817b254": "e-con-full e-flex e-con e-parent",
  "819e0b0": "elementor-widget elementor-widget-spacer",
  "81f7b20": "e-con-full e-flex e-con e-child",
  "821a193": "elementor-widget elementor-widget-ideapark-accordion",
  "82a7228": "elementor-widget elementor-widget-text-editor",
  "8324485": "elementor-widget elementor-widget-spacer",
  "83789f5": "e-con-full e-flex e-con e-child",
  "8397c78": "e-con-full e-flex e-con e-parent",
  "83ace67": "elementor-widget elementor-widget-ideapark-button",
  "83b9298": "e-con-full e-flex e-con e-parent",
  "84f1445": "elementor-widget elementor-widget-heading",
  "850c797": "elementor-widget elementor-widget-text-editor",
  "85180a7": "e-con-full e-flex e-con e-parent",
  "85d3801": "e-con-full e-flex e-con e-parent",
  "8700216": "e-con-full e-flex e-con e-parent",
  "87483c9": "e-con-full e-flex e-con e-parent",
  "8788f93": "elementor-widget elementor-widget-image",
  "879e238": "elementor-widget elementor-widget-spacer",
  "885905c": "elementor-widget elementor-widget-spacer",
  "8909acd": "e-con-boxed e-flex e-con e-parent",
  "89314c3": "elementor-widget elementor-widget-spacer",
  "89aa6f5": "e-con-full e-flex e-con e-parent",
  "8a0d58c": "e-con-full e-flex e-con e-parent",
  "8a79c35": "e-con-full e-flex e-con e-parent",
  "8b24048": "e-con-full e-flex e-con e-parent",
  "8c281d6": "elementor-widget__width-initial elementor-widget elementor-widget-heading",
  "8c34037": "e-con-full e-flex e-con e-parent",
  "8cdc080": "elementor-widget elementor-widget-heading",
  "8cddfad": "elementor-widget elementor-widget-heading",
  "8ec8d7d": "elementor-widget__width-initial elementor-widget elementor-widget-heading",
  "8ee83a5": "elementor-widget elementor-widget-image",
  "8f95afd": "elementor-widget elementor-widget-spacer",
  "915e4e5": "elementor-widget elementor-widget-spacer",
  "91883ea": "elementor-widget elementor-widget-heading",
  "91dad7c": "elementor-widget elementor-widget-spacer",
  "9232bad": "e-con-full e-flex e-con e-parent",
  "92b6393": "elementor-widget elementor-widget-heading",
  "92c3232": "e-flex e-con-boxed e-con e-parent",
  "92e7c2c": "elementor-widget elementor-widget-heading",
  "9407c6b": "e-con-full e-flex e-con e-parent",
  "96d7d02": "e-con-full e-flex e-con e-parent",
  "97b044b": "e-con-full e-flex e-con e-parent",
  "97f0368": "elementor-widget elementor-widget-text-editor",
  "984c133": "elementor-widget elementor-widget-spacer",
  "98ef431": "e-con-full e-flex e-con e-parent",
  "99550df": "elementor-widget elementor-widget-spacer",
  "99d1d95": "elementor-widget elementor-widget-heading",
  "9ab83b1": "e-con-full e-flex e-con e-parent",
  "9b433c1": "elementor-widget elementor-widget-heading",
  "9bb1fd1": "e-con-full e-transform elementor-hidden-desktop elementor-hidden-tablet elementor-hidden-mobile e-flex e-con e-child",
  "9bb4e1d": "elementor-widget__width-initial elementor-widget elementor-widget-ideapark-banners",
  "9c0c13c": "e-con-full e-flex e-con e-parent",
  "9c7b662": "elementor-widget elementor-widget-heading",
  "9c903e5": "e-con-full e-flex e-con e-child",
  "9c917cf": "elementor-widget elementor-widget-heading",
  "9d478bc": "e-con-full e-flex e-con e-child",
  "9e18b8a": "elementor-widget elementor-widget-heading",
  "9e9a2bd": "elementor-widget elementor-widget-heading",
  "9fe9e3e": "elementor-widget elementor-widget-text-editor",
  "a0236c5": "e-con-full h-full animated-slow e-flex e-con e-child",
  "a046fd9": "e-con-full e-flex e-con e-parent",
  "a0a16d1": "elementor-widget elementor-widget-spacer",
  "a0b127f": "e-con-full e-flex e-con e-parent",
  "a0b34fe": "elementor-widget elementor-widget-spacer",
  "a0d4448": "e-flex e-con-boxed e-con e-child",
  "a18c39e": "elementor-widget elementor-widget-spacer",
  "a2383ea": "e-con-full e-flex e-con e-parent",
  "a27c36c": "e-con-full e-flex e-con e-parent",
  "a2f9f29": "elementor-widget elementor-widget-spacer",
  "a39cd47": "elementor-widget elementor-widget-spacer",
  "a41d512": "elementor-widget elementor-widget-spacer",
  "a49aa15": "elementor-widget elementor-widget-spacer",
  "a5d10e4": "elementor-widget elementor-widget-heading",
  "a652fb2": "e-con-full e-flex e-con e-parent",
  "a666edc": "e-flex e-con-boxed e-con e-parent",
  "a7707ab": "e-con-full h-full e-flex e-con e-child",
  "a786cdf": "elementor-widget elementor-widget-heading",
  "a7b6fbb": "e-con-full h-full animated-slow e-flex e-con e-child",
  "a86debb": "elementor-widget elementor-widget-heading",
  "a8a782a": "e-con-full e-flex e-con e-child",
  "a8fe8ba": "e-con-full e-flex e-con e-parent",
  "a99bcf1": "elementor-widget elementor-widget-spacer",
  "a9e0ab2": "elementor-widget elementor-widget-spacer",
  "ab3aad8": "elementor-widget elementor-widget-ideapark-accordion",
  "abc2a12": "elementor-widget elementor-widget-heading",
  "ac769fd": "e-con-full e-flex e-con e-parent",
  "accace8": "e-con-full e-flex e-con e-parent",
  "acdb85e": "elementor-widget elementor-widget-heading",
  "acde742": "e-con-full e-flex e-con e-parent",
  "adad302": "elementor-widget elementor-widget-ideapark-countdown",
  "ae4be08": "e-con-full e-flex e-con e-parent",
  "aee9066": "e-con-full e-flex e-con e-parent",
  "af7308c": "elementor-widget elementor-widget-heading",
  "b084218": "e-con-boxed e-flex e-con e-parent",
  "b10e50f": "elementor-widget elementor-widget-heading",
  "b1cc51b": "elementor-widget elementor-widget-spacer",
  "b1f947a": "elementor-widget elementor-widget-heading",
  "b21ac61": "elementor-widget elementor-widget-ideapark-button",
  "b23991d": "e-con-full e-flex e-con e-parent",
  "b23def5": "e-con-full e-flex e-con e-parent",
  "b2e8a7d": "e-con-full e-flex e-con e-child",
  "b32b793": "elementor-widget elementor-widget-heading",
  "b373aad": "elementor-widget elementor-widget-spacer",
  "b3dd99a": "elementor-widget elementor-widget-heading",
  "b4b95b5": "elementor-widget elementor-widget-heading",
  "b4e410a": "e-con-full h-full animated-slow e-flex e-con e-child",
  "b4f3215": "e-con-full e-flex e-con e-parent",
  "b509fe5": "elementor-widget elementor-widget-spacer",
  "b58feca": "e-con-full e-flex e-con e-parent",
  "b638944": "elementor-widget elementor-widget-heading",
  "b695f51": "h-scroll-down-arrow elementor-hidden-mobile elementor-widget elementor-widget-image",
  "b6a3ee0": "elementor-widget elementor-widget-text-editor",
  "b7839aa": "e-con-full e-flex e-con e-parent",
  "b80eb2a": "elementor-widget elementor-widget-spacer",
  "b8f7884": "e-con-full e-flex e-con e-parent",
  "b8feb54": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "b9125c2": "e-con-full e-flex e-con e-parent",
  "b9592dd": "elementor-widget elementor-widget-heading",
  "b9df5a9": "elementor-widget elementor-widget-heading",
  "bc9cd96": "elementor-widget elementor-widget-spacer",
  "bcc9536": "elementor-widget elementor-widget-text-editor",
  "bd2665c": "elementor-widget elementor-widget-spacer",
  "bd43228": "elementor-widget elementor-widget-text-editor",
  "bde5c09": "e-con-full e-flex e-con e-parent",
  "bf12cd1": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "bfab6f5": "e-con-full e-flex e-con e-parent",
  "c0cf56a": "elementor-widget elementor-widget-ideapark-button",
  "c27a11f": "e-con-full e-flex e-con e-parent",
  "c2ae116": "elementor-widget elementor-widget-text-editor",
  "c343565": "e-con-full e-flex e-con e-parent",
  "c422bb8": "elementor-widget elementor-widget-heading",
  "c452c85": "elementor-widget elementor-widget-spacer",
  "c4837f2": "elementor-widget elementor-widget-text-editor",
  "c4e86c3": "elementor-widget elementor-widget-spacer",
  "c4fedcd": "e-con-full e-flex e-con e-parent",
  "c52effb": "elementor-widget elementor-widget-spacer",
  "c620d22": "e-con-full e-flex e-con e-parent",
  "c66738d": "elementor-widget elementor-widget-spacer",
  "c7b3967": "elementor-widget elementor-widget-heading",
  "c87d2b7": "e-con-full e-flex e-con e-parent",
  "c8e09fd": "e-con-full e-flex e-con e-parent",
  "c8ede4d": "e-con-full e-flex e-con e-parent",
  "c9d3cf9": "e-con-full e-flex e-con e-parent",
  "c9d8b57": "elementor-widget elementor-widget-heading",
  "c9e7cac": "elementor-widget elementor-widget-heading",
  "caa5a38": "elementor-widget elementor-widget-image",
  "cb0382d": "e-con-full e-flex e-con e-child",
  "cbdce72": "elementor-widget elementor-widget-text-editor",
  "cd08c4c": "e-con-full e-flex e-con e-child",
  "cd6aca4": "elementor-widget elementor-widget-heading",
  "cd851c7": "elementor-widget elementor-widget-shortcode",
  "ce40913": "elementor-widget elementor-widget-spacer",
  "cf8fca8": "elementor-widget elementor-widget-spacer",
  "d03e7d3": "elementor-widget elementor-widget-heading",
  "d06b2af": "e-con-full e-flex e-con e-child",
  "d07d91e": "elementor-widget elementor-widget-text-editor",
  "d17f084": "e-con-full e-flex e-con e-child",
  "d1c0274": "elementor-widget elementor-widget-text-editor",
  "d2a8c07": "e-con-boxed e-flex e-con e-parent",
  "d3178cb": "elementor-widget elementor-widget-image",
  "d3878e1": "e-con-full e-flex e-con e-parent",
  "d39a3ea": "elementor-widget elementor-widget-heading",
  "d3c16b6": "elementor-widget elementor-widget-heading",
  "d3c69a5": "elementor-widget elementor-widget-heading",
  "d3ef821": "elementor-widget elementor-widget-heading",
  "d479905": "elementor-widget elementor-widget-heading",
  "d4a9169": "e-con-full e-flex e-con e-child",
  "d4cec09": "elementor-widget elementor-widget-heading",
  "d5a1b75": "elementor-widget-tablet__width-inherit elementor-hidden-mobile elementor-widget elementor-widget-heading",
  "d60027d": "elementor-widget elementor-widget-spacer",
  "d6ce21e": "e-con-full e-flex e-con e-parent",
  "d6e997b": "elementor-widget elementor-widget-heading",
  "d746a7f": "e-con-full e-flex e-con e-parent",
  "d778d07": "e-con-full e-flex e-con e-parent",
  "d81c94e": "e-con-full e-flex e-con e-parent",
  "d8a1ee0": "elementor-widget elementor-widget-spacer",
  "d8a29e9": "e-con-full e-flex e-con e-parent",
  "d8c7078": "elementor-widget elementor-widget-spacer",
  "d90cd32": "elementor-widget elementor-widget-spacer",
  "d911c8f": "elementor-widget elementor-widget-heading",
  "da52695": "elementor-widget elementor-widget-heading",
  "db31ca0": "elementor-widget elementor-widget-heading",
  "db8f9b0": "e-con-full e-flex e-con e-parent",
  "dd0d84c": "e-flex e-con-boxed e-con e-parent",
  "dd30e96": "elementor-widget elementor-widget-heading",
  "ddcd4b9": "elementor-widget elementor-widget-spacer",
  "dde6c42": "e-con-full e-flex e-con e-parent",
  "de6755e": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "de8ec32": "elementor-widget elementor-widget-heading",
  "dee1d64": "elementor-widget elementor-widget-spacer",
  "df61ee9": "elementor-widget elementor-widget-spacer",
  "e051e39": "elementor-widget elementor-widget-heading",
  "e06c50a": "e-con-full e-flex e-con e-parent",
  "e0b78e4": "elementor-widget elementor-widget-heading",
  "e0da4b7": "elementor-widget elementor-widget-spacer",
  "e0e36fc": "elementor-widget elementor-widget-text-editor",
  "e15665f": "e-con-full e-flex e-con e-parent",
  "e287fe3": "elementor-widget elementor-widget-spacer",
  "e2a9d40": "elementor-widget elementor-widget-spacer",
  "e31b185": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "e3e256b": "elementor-widget elementor-widget-heading",
  "e439096": "e-con-full e-flex e-con e-parent",
  "e46f2e9": "elementor-widget elementor-widget-heading",
  "e475474": "elementor-widget elementor-widget-ideapark-running-line",
  "e4e8094": "elementor-widget__width-initial elementor-widget elementor-widget-image",
  "e5358d4": "e-con-full e-flex e-con e-parent",
  "e553ae2": "e-con-boxed e-flex e-con e-parent",
  "e605abf": "e-con-full e-flex e-con e-parent",
  "e649f4a": "e-con-full e-flex e-con e-child",
  "e6b7729": "e-con-full e-flex e-con e-parent",
  "e6bd30d": "elementor-widget elementor-widget-heading",
  "e72e321": "elementor-widget elementor-widget-heading",
  "e7c8ff7": "e-con-full e-flex e-con e-parent",
  "e8095dd": "elementor-widget elementor-widget-heading",
  "e88ed4d": "elementor-widget elementor-widget-text-editor",
  "e9a4258": "e-con-full e-flex e-con e-parent",
  "eac7712": "e-con-full e-flex e-con e-parent",
  "eb5c98c": "elementor-widget elementor-widget-spacer",
  "eb8adfb": "e-con-full e-flex e-con e-parent",
  "ec11e5d": "elementor-widget elementor-widget-spacer",
  "ecbbc0d": "elementor-widget elementor-widget-heading",
  "ed2252b": "e-flex e-con-boxed e-con e-parent",
  "ed895a9": "elementor-widget elementor-widget-heading",
  "ee8b344": "e-con-full e-flex e-con e-parent",
  "ee9901a": "elementor-widget elementor-widget-heading",
  "eeebf70": "elementor-widget elementor-widget-spacer",
  "ef276ff": "e-con-full e-flex e-con e-parent",
  "efc4030": "elementor-widget elementor-widget-ideapark-accordion",
  "efe68f6": "elementor-widget elementor-widget-heading",
  "f013833": "elementor-widget elementor-widget-ideapark-button",
  "f07185a": "elementor-widget elementor-widget-spacer",
  "f093dc2": "elementor-widget elementor-widget-spacer",
  "f0e256a": "e-con-boxed e-flex e-con e-parent",
  "f15bbd6": "e-con-full e-flex e-con e-parent",
  "f16d91f": "elementor-widget elementor-widget-spacer",
  "f17e0b8": "e-con-full e-flex e-con e-child",
  "f23854f": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "f2c01f2": "e-flex e-con-boxed e-con e-parent",
  "f2d301a": "elementor-widget elementor-widget-spacer",
  "f35351b": "elementor-widget elementor-widget-text-editor",
  "f4cdc43": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "f51a47b": "elementor-widget elementor-widget-spacer",
  "f555e75": "e-con-full e-flex e-con e-child",
  "f55f766": "elementor-widget elementor-widget-heading",
  "f56bf0d": "e-con-boxed e-flex e-con e-parent",
  "f69618b": "e-con-full e-flex e-con e-parent",
  "f6e17b1": "elementor-widget elementor-widget-text-editor",
  "f75931f": "elementor-widget elementor-widget-spacer",
  "f834966": "e-con-full h-full e-flex e-con e-parent",
  "f8f3a43": "elementor-widget elementor-widget-heading",
  "f95557b": "elementor-widget elementor-widget-heading",
  "f976564": "e-con-boxed e-flex e-con e-parent",
  "f9c7e12": "elementor-widget elementor-widget-spacer",
  "fa2b0a4": "h-scroll-down-arrow elementor-hidden-mobile elementor-widget elementor-widget-image",
  "fa3540c": "e-con-full e-flex e-con e-parent",
  "fa5cbcc": "elementor-widget elementor-widget-heading",
  "fa83c11": "elementor-icon-list--layout-traditional elementor-list-item-link-full_width elementor-widget elementor-widget-icon-list",
  "fa95dbd": "elementor-widget elementor-widget-text-editor",
  "faae841": "elementor-widget elementor-widget-heading",
  "fb19423": "elementor-widget elementor-widget-heading",
  "fc440a5": "elementor-widget elementor-widget-heading",
  "fc89ab2": "elementor-widget elementor-widget-spacer",
  "fca5d4d": "elementor-widget elementor-widget-heading",
  "fd6035c": "e-con-full e-flex e-con e-parent",
  "fe3f0a0": "e-con-full e-flex e-con e-child",
  "fedb541": "elementor-widget elementor-widget-heading",
  "fee13d5": "elementor-widget elementor-widget-spacer",
};
